### ISSUE TITLE
Unable to open standalone app when using FNM

### ISSUE THREAD

**Issue by claylevering** [vuejs/devtools-next#165]
Hi team!

I do not have a globally installed instance of Node - all of my projects leverage [FNM](https://github.com/Schniz/fnm) to ensure proper Node / NPM versions per-project.  This means I have dozens of installed Node versions and - depending on which project folder I am currently in, FNM resolves `where node` (think `virtualenv`):

```
$ where node
# /Users/claylevering/Library/Caches/fnm_multishells/18102_1704998236442/bin/node/opt/homebrew/bin/node

ls ~/Library/Caches/fnm_multishells/
lrwxr-xr-x      1 claylevering  staff    67B Aug 31  2022 99905_1661961411744 -> /Users/claylevering/Library/Application Support/fnm/aliases/default
lrwxr-xr-x      1 claylevering  staff    87B Sep 18 20:33 99922_1695094397625 -> /Users/claylevering/Library/Application Support/fnm/node-versions/v18.17.1/installation
lrwxr-xr-x      1 claylevering  staff    87B Dec  7  2022 99927_1670452676313 -> /Users/claylevering/Library/Application Support/fnm/node-versions/v16.18.1/installation
lrwxr-xr-x      1 claylevering  staff    87B Oct 28  2022 99937_1666962067508 -> /Users/claylevering/Library/Application Support/fnm/node-versions/v16.18.0/installation
lrwxr-xr-x      1 claylevering  staff    67B Jun 30  2023 99939_1688141388489 -> /Users/claylevering/Library/Application Support/fnm/aliases/default
lrwxr-xr-x      1 claylevering  staff    67B Mar 21  2023 99940_1679440025859 -> /Users/claylevering/Library/Application Support/fnm/aliases/default
lrwxr-xr-x      1 claylevering  staff    67B Mar 17  2022 99947_1647536168688 -> /Users/claylevering/Library/Application Support/fnm/aliases/default
lrwxr-xr-x      1 claylevering  staff    67B Oct  3 07:05 99949_1696341942519 -> /Users/claylevering/Library/Application Support/fnm/aliases/default
lrwxr-xr-x      1 claylevering  staff    87B May  2  2023 9994_1683039845575 -> /Users/claylevering/Library/Application Support/fnm/node-versions/v18.11.0/installation
lrwxr-xr-x      1 claylevering  staff    87B Oct 12 10:04 99952_1697130273340 -> /Users/claylevering/Library/Application Support/fnm/node-versions/v18.17.1/installation
lrwxr-xr-x      1 claylevering  staff    67B Sep 20  2022 99957_1663694639194 -> /Users/claylevering/Library/Application Support/fnm/aliases/default
lrwxr-xr-x      1 claylevering  staff    67B Feb 27  2023 99958_1677536496552 -> /Users/claylevering/Library/Application Support/fnm/aliases/default
lrwxr-xr-x      1 claylevering  staff    67B Sep 15  2022 99959_1663303755372 -> /Users/claylevering/Library/Application Support/fnm/aliases/default
lrwxr-xr-x      1 claylevering  staff    87B Dec 18 08:51 99959_1702918292637 -> /Users/claylevering/Library/Application Support/fnm/node-versions/v18.18.2/installation
lrwxr-xr-x      1 claylevering  staff    87B Nov 17  2022 9995_1668727919420 -> /Users/claylevering/Library/Application Support/fnm/node-versions/v16.18.1/installation
lrwxr-xr-x      1 claylevering  staff    67B May  2  2023 99962_1683035042941 -> /Users/claylevering/Library/Application Support/fnm/aliases/default
lrwxr-xr-x      1 claylevering  staff    67B Mar 17  2022 99968_1647536168710 -> /Users/claylevering/Library/Application Support/fnm/aliases/default
lrwxr-xr-x      1 claylevering  staff    67B Feb 15  2023 99971_1676478717882 -> /Users/claylevering/Library/Application Support/fnm/aliases/default
lrwxr-xr-x      1 claylevering  staff    67B Sep 21  2022 99985_1663821738174 -> /Users/claylevering/Library/Application Support/fnm/aliases/default
lrwxr-xr-x      1 claylevering  staff    67B Feb 23  2023 99987_1677188798504 -> /Users/claylevering/Library/Application Support/fnm/aliases/default
lrwxr-xr-x      1 claylevering  staff    87B Sep 21 16:43 99995_1695339789149 -> /Users/claylevering/Library/Application Support/fnm/node-versions/v18.17.1/installation
lrwxr-xr-x      1 claylevering  staff    67B Nov 17  2022 999_1668724589600 -> /Users/claylevering/Library/Application Support/fnm/aliases/default
```

I will be honest this type of global package has broken from these types of configurations for other apps (notably earlier versions of VS Code).  This is a very common practice to enforce project consistency in larger microservice driven organizations (either through FNM of nvm) and is obviously very common in the Python world with venv, etc.

Both `npx vue-devtools` and `npm i -g @vue/devtools && vue-devtools` fail to launch with the attached screenshot.  Here's the console output:

```
npx vue-devtools
file:///Users/claylevering/Library/Application%20Support/fnm/node-versions/v18.18.2/installation/lib/node_modules/@vue/devtools/node_modules/execa/lib/error.js:60
		error = new Error(message);
		        ^

Error: Command failed with exit code 1: /Users/claylevering/Library/Application Support/fnm/node-versions/v18.18.2/installation/lib/node_modules/@vue/devtools/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron /Users/claylevering/Library/Application%20Support/fnm/node-versions/v18.18.2/installation/lib/node_modules/@vue/devtools/node_modules/@vue/devtools-electron/dist/app.cjs
    at makeError (file:///Users/claylevering/Library/Application%20Support/fnm/node-versions/v18.18.2/installation/lib/node_modules/@vue/devtools/node_modules/execa/lib/error.js:60:11)
    at execaSync (file:///Users/claylevering/Library/Application%20Support/fnm/node-versions/v18.18.2/installation/lib/node_modules/@vue/devtools/node_modules/execa/index.js:201:17)
    at file:///Users/claylevering/Library/Application%20Support/fnm/node-versions/v18.18.2/installation/lib/node_modules/@vue/devtools/node_modules/@vue/devtools-electron/dist/cli.mjs:7:16
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  shortMessage: 'Command failed with exit code 1: /Users/claylevering/Library/Application Support/fnm/node-versions/v18.18.2/installation/lib/node_modules/@vue/devtools/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron /Users/claylevering/Library/Application%20Support/fnm/node-versions/v18.18.2/installation/lib/node_modules/@vue/devtools/node_modules/@vue/devtools-electron/dist/app.cjs',
  command: '/Users/claylevering/Library/Application Support/fnm/node-versions/v18.18.2/installation/lib/node_modules/@vue/devtools/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron /Users/claylevering/Library/Application%20Support/fnm/node-versions/v18.18.2/installation/lib/node_modules/@vue/devtools/node_modules/@vue/devtools-electron/dist/app.cjs',
  escapedCommand: '"/Users/claylevering/Library/Application Support/fnm/node-versions/v18.18.2/installation/lib/node_modules/@vue/devtools/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron" "/Users/claylevering/Library/Application%20Support/fnm/node-versions/v18.18.2/installation/lib/node_modules/@vue/devtools/node_modules/@vue/devtools-electron/dist/app.cjs"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  cwd: '/Users/claylevering/Repos/REPO-NAME',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.18.2
```

![image](https://github.com/vuejs/devtools-next/assets/745536/667b4653-3820-4ecc-b118-ae7c9ce34de8)

**Comment by alexzhang1030** [comment]
Hey, can you share if this file path exists?

![image](https://github.com/vuejs/devtools-next/assets/49969959/aab8c66c-842c-4b72-9cb6-02fd04c047ce)

**Comment by alexzhang1030** [comment]
BTW, I also use fnm, and this is my node path:

```bash
$ which node
/Users/alex/Library/Caches/fnm_multishells/24345_1705026172740/bin/node
```

I don't know why your node path is different from mine. Can you checkout your configure?

```bash
# it's includes `homebrew`, why?
/Users/claylevering/Library/Caches/fnm_multishells/18102_1704998236442/bin/node/opt/homebrew/bin/node
```

**Comment by claylevering** [comment]
Yes, it does:

![image](https://github.com/vuejs/devtools-next/assets/745536/9a82798c-3a58-4d3b-a238-8ff4af21f777)

And FNM is listed in my `brew ls` command - is it possible it resolves from an [FNM upgrade command](https://github.com/Schniz/fnm?tab=readme-ov-file#upgrade) (which seems **_potentially_** different than their install script?).

I'm going to purge FNM from brew, scrub my shell out a bit and then try this again.  Reporting back shortly.

**Comment by claylevering** [comment]
Ugh - unfortunately not.

![image](https://github.com/vuejs/devtools-next/assets/745536/3685cac1-64cc-4ff2-a557-913b968b4a56)

stat /Users/claylevering/Library/Application\ Support/fnm/node-versions/v18.19.0/installation/lib/node_modules/@vue/devtools/node_modules/@vue/devtools-electron/dist/app.cjs
16777229 320880160 -rw-r--r-- 1 claylevering staff 0 1923 "Jan 12 08:53:55 2024" "Jan 12 08:53:55 2024" "Jan 12 08:53:55 2024" "Jan 12 08:53:55 2024" 4096 8 0 /Users/claylevering/Library/Application Support/fnm/node-versions/v18.19.0/installation/lib/node_modules/@vue/devtools/node_modules/@vue/devtools-electron/dist/app.cjs

**Comment by niekbridge** [comment]
Hi,

I have exactly the same problem. I hope this does not distract from the above as my setup is quite different.

Node is installed via NVM and vue devtools is installed in a PNPM monorepo. 
The execution path exists and `app.cjs` is present in the folder.

Installing devtools in the root of the monorepo did not resolve the issue.
When I installed it in a non-monorepo with PNPM as package manager everything worked fine.

![Screenshot 2024-01-16 at 17 48 58](https://github.com/vuejs/devtools-next/assets/78557728/d02da28a-5092-44f2-a6f0-5fe02cf2adaf)
![Screenshot 2024-01-16 at 17 49 18](https://github.com/vuejs/devtools-next/assets/78557728/4e4e2aeb-3fbc-45f3-948c-59b9c9795a70)

**Comment by niekbridge** [comment]
Hi,

I've done some more testing and when there are no whitespaces in the absolute path, everything loads correctly. Could it be that somehow whitespace is causing trouble in loading the electron execution file?
